<<<<<<< HEAD
title: Ashwin KS blog
description: My personal blog on projects and learning in Data Science,Machine learning,Analytics field.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
=======
theme: jekyll-theme-slate
>>>>>>> 73623e92e8765b86d4da3a4c2eb1be9d5956bfaf
